### ISSUE TITLE
Docker image shutting down after a few days

### ISSUE THREAD

**Issue by Mange** [izderadicka/audioserve#16]
I'm running the service inside the official docker image and proxy it via nginx + let's encrypt. After a few days the process exits with status code 0 and no log output, making nginx shut down (for domain name reasons with docker-compose; but that's not the issue here).

Is there some way I can try to debug this problem? I'm pretty confident in Rust, but it's also running on a server with limited hardware, so recompiling constantly is probably not going to work for me.

It's happened four times now, so I'm now turning on `restart: unless-stopped` to work around it, but getting to the cause of the issue would be preferred by me.

The little information I can give:

1. Process had no output. Exit status 0.
2. The most I've been able to have the container running at a time: Around 3 days.
3. Service works well when it's running (although it emits a lot of warnings about upgrading websockets.
4. Memory pressure on the server is fine. It was not killed by OOM killer according to `docker inspect` either.
5. CPU usage has been low up until the service died.
6. No problem with disk space.
7. Server has had no network interruptions during this time.
8. No other container (I run around 11 of them) has any similar issues.
9. Server is my own hardware at home, not a cloud host or a VM. No hardware issues that I know of, and it's pretty new.

I'm sorry I cannot give any more information. This "issue" is literally me asking for ideas on what to look for so I *can* give you better information.

**Comment by izderadicka** [comment]
Are you using provided Dockerfile for alpine linux?
What exact config/ rguments are you using to run program?

To  get more detailed logging (debug) you'll need to compile in debug mode (without --release, binary then will be in target/debug) and set environment variable to RUST_LOG=debug (which will log debug from all creates) or just RUST_LOG=audioserve=debug - to log only debug messages from this binary.

You can also try to strip down features you are not using - compile with --no-default-features and then --features you want. This will leave out unwanted code in case it causes problems.

When exactly the termination of container happens?

- when streaming some music?
- when working with files in collections directories (copying new, renaming etc)?
- or when audioserve is unused?

As exist status is 0 I assume it's not segfault or some other OS enforced termination.

**Comment by izderadicka** [comment]
Also looking now at default logging when running in Docker container it was not ideal - although info logging is enabled for release build, it's not enabled by adding appropriate env. variable (I've fixed it in latest master). 
So at least I would recommend to have `ENV RUST_LOG=audioserve=info` in docker file, then you can see if program terminated normally - as this message should be last one:
```
INFO  audioserve > Server finished
```

**Comment by Mange** [comment]
I run it using the docker-compose configuration:

```yml
    audioserve:
      image: izderadicka/audioserve
      container_name: audioserve
      command: ["--allow-symlinks", "/audiobooks"]
      volumes:
        - /home/mange/services/audioserve/config:/home/audioserve/.audioserve
        - /home/mange/services/audioserve/library:/audiobooks
      env_file:
        - /home/mange/services/audioserve/config/secrets.env
      restart: unless-stopped
```

It happens when the service is not used.

I'll see about recompiling it and trying the debug logs for a bit, but now it's been running without issue for 4 days. I'll recompile it the next time it crashes, just before I also capture the whole output of `docker inspect` so I had additional clues.
