### ISSUE TITLE
Volume Permission issue on Synology NAS

### ISSUE THREAD

**Issue by knogwak** [izderadicka/audioserve#66]
I am after some advice on a rather niche issue if you have the time. ! am attempting to use your docker build on a Synolgy NAS and I have struck a permission issue with the /audiobooks volume. For their own reasons Synology start User IDs at >1024 and recommend against using numbers <1025 for users as this may break things.

Using this deocker-compose.yml
```
version: "2.1"
services:
  audioserve:
    image: izderadicka/audioserve
    container_name: audioserve
    command:  --no-authentication /audiobooks
    environment:
      - PUID=1027
      - PGID=100
    volumes:
      - /volume1/audiobooks:/audiobooks
    ports:
      - 3000:3000
    restart: unless-stopped
```

The container runs and I get permission errors accessing the audiobooks. Looking inside the container I can see this:
```
sudo docker exec --privileged audioserve ls -al /
total 0
drwxr-xr-x    1 root     root           174 Oct 20 01:35 .
drwxr-xr-x    1 root     root           174 Oct 20 01:35 ..
-rwxr-xr-x    1 root     root             0 Oct 20 01:35 .dockerenv
drwx------    1 1027     users         1888 Oct 19 05:35 audiobooks
drwxr-xr-x    1 audioser audioser        38 Sep 12 21:45 audioserve
<snip>
```
The issue seems to be that the audioserve user is uid/gid 1000. I assume this would work fine on a standard linux build where the 1st user is generally uid 1000 but breaks on the synology where i can not use uid 1000. 

I am not sure how I can resolve this problem. Thanks for any advice

**Comment by knogwak** [comment]
Just for future reference, here is a working docker command for the synology NAS:

`docker run --name audioserve -p 3000:3000 -v /volume1/docker/audioserve/audioserve-data:/audioserve-data -v /volume1/static/audiobooks:/audiobooks --user 1027 izderadicka/audioserve --no-authentication --data-dir /audioserve-data /audiobooks`

**Comment by knogwak** [comment]
Also, here is a simple docker-compose file:

```
---
version: "2.1"
services:
  audioserve:
    image: izderadicka/audioserve
    user: "1027"
    container_name: audioserver
    command: --no-authentication --tags --data-dir /audioserve-data /audiobooks
#   environment:
#      - RUST_BACKTRACE=full
    volumes:
      - /volume1/docker/audioserve/audioserve-data:/audioserve-data
      - /volume1/static/audiobooks:/audiobooks
    ports:
      - 3000:3000
    restart: unless-stopped
```
