### ISSUE TITLE
[Suggestion] Moving guide and use from shell and run towards compose.

### ISSUE THREAD

**Issue by BansheeHero** [izderadicka/audioserve#77]
Hi,

Since both docker and podman are now using compose files I think it would be nice to do the same.
The benefits are:
1. Easier deployment and auto-update solo or with other services
2. Easier guides and support (We can see and help users adjust their compose files.)
As well as the opportunity to restructure the `README.md` file.

Turning something like this:
```
# Security risk: Loading JSON from a remote share.
docker run -d --name audioserve_nfs -p 3000:3000 \
        --user 1099:3000 \
        -v /mnt/share/audiobooks/cz:/audiobooks/cz \
        -v /mnt/share/audiobooks/en:/audiobooks/en \
        -v /mnt/share/audiobooks/digest:/audiobooks/digest \
        -v /mnt/share/audiobooks/audioserve/:/home/audioserve/.audioserve \
        -e AUDIOSERVE_SHARED_SECRET=yourpassword \
        izderadicka/audioserve \
                --tags \
                --behind-proxy \
                --transcoding-max-parallel-processes 24 \
                --positions-backup-file /home/audioserve/.audioserve/positions-backup.json \
                --positions-backup-schedule "0 3 * * *" \
        /audiobooks/cz \
        /audiobooks/en \
        audiobooks/digest
```
Into something compatible with compose. I am not versed well with docker so I am still trying to write it.
Any suggestions?

```
version: '3'
services:
  audioserve:
    image: izderadicka/audioserve
    restart: always
    ser: "1099:3000"
    ports:
      - "3000:3000/tcp"
    volumes:
      - /mnt/share/audiobooks/audioserve/:/home/audioserve/.audioserve
      - /mnt/share/audiobooks/en:/audiobooks/en
      - /mnt/share/audiobooks/digest:/audiobooks/digest
      - /mnt/share/audiobooks/cz:/audiobooks/cz
    environment:
      AUDIOSERVE_SHARED_SECRET: yourpassword
    entrypoint:
      - audioserve
      - --tags
      - --behind-proxy
      - --transcoding-max-parallel-processes 24
      - --positions-backup-file /home/audioserve/.audioserve/positions-backup.json
      - --positions-backup-schedule "0 3 * * *"
      - /audiobooks/cz
      - /audiobooks/en
      - audiobooks/digest
```

Moving away from command-line syntax should be great for the project and systems that support compose are growing. (and CLI is still functional on `docker` and `podman`)

What do you think?
