### ISSUE TITLE
Natural Ordering of files

### ISSUE THREAD

**Issue by J4gQBqqR** [izderadicka/audioserve#89]
Current order: 137 will be between 1369 and 1370.
Natural ordering should be: 1, 2, 3, ... 137 ... 1369, 1370, ...

**Comment by J4gQBqqR** [comment]
![图片](https://user-images.githubusercontent.com/77554817/207735268-c7391b73-de55-4adb-8805-16cd492adb9a.png)

**Comment by izderadicka** [comment]
Current ordering is just string ordering (with some optional UTF collation - see readme). 
But you're right natural ordering for leading numbers could be usefull.  
Up to now I have been using script to add leading zeros file names so the ordering is correct in all cases.

This could be good optional feature.

**Comment by izderadicka** [comment]
Implemented in master branch, enabled by default unless `--no-files-natural-ordering` argument is passed.
May require reload of collections cache (by starting with `--force-cache-update` or by sending SIGUSR1 signal to running process)

**Comment by J4gQBqqR** [comment]
Hi, I restarted the docker image by `--force-cache-update`, but the ordering is still like the old order. 
Is it because the unstable docker image still does not have this feature yet?

```
  audioserve:
    image: izderadicka/audioserve:unstable
    container_name: audioserve
    restart: always
    networks:
      qi_default:
        ipv4_address: 172.18.0.41
    user: 9030:9030
    command: >-
      --collapse-cd-folders
      --force-cache-update
      --behind-proxy
      --transcoding-max-parallel-processes 20
      --positions-backup-file /.audioserve/positions-backup.json
      --data-dir /.audioserve
      /audiobooks
    environment:
      - PUID=9030
      - PGID=9030
      - "AUDIOSERVE_SHARED_SECRET=y!%59R@QSuGQxR&PUDDQq*kL%U6^MR"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - "/home/media/config/audioserve:/.audioserve"
      - "/home/media/audiobooks:/audiobooks:ro"
```

![图片](https://user-images.githubusercontent.com/77554817/218269586-38b6f4b2-20f7-4b7c-903b-cdf8c8f89dba.png)
